/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'estudiante' at '20/10/17 8:34' with Gradle 3.0
 *
 * @author estudiante, @date 20/10/17 8:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
